### ISSUE TITLE
False positive when a formal is matched in a method but not used

### ISSUE THREAD

**Issue by jimhester** [hadley/ellipsis#1]
IMHO this should not cause a warning, as `a` was matched by the method, just not used in the body.

``` r
library(ellipsis)

foo <- function(x, ...) {
  ellipsis::check_dots_used()
  UseMethod("foo")
}

foo.character <- function(x, ..., a) {
  x
}

foo("hi", a = 1)
#> Warning: Some components of ... were not used: a
#> [1] "hi"
```

Created on 2018-07-09 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
I don't think I have any way to detect that 😞 

And the warning is correct: `a` isn't used
